# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: dask_cudf
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
  run:
    - python
    - cudf
    - dask >=0.19.0
    - distributed >=1.23.0
    - pandas 0.20.3
test:
  imports:
    - dask_cudf

about:
  home: http://rapids.ai
  license: Apache
  # license_file: LICENSE
  summary: A Partitioned GPU Dataframe
