# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: dask_cudf
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  path: ../../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python x.x
    - cudf 0.6*
    - dask >=0.19.0
    - distributed >=1.23.0
  run:
    - python x.x
    - cudf 0.6*
    - dask >=0.19.0
    - distributed >=1.23.0
test:
  imports:
    - dask_cudf

about:
  home: http://rapids.ai
  license: Apache
  license_file: ../../../LICENSE.txt
  summary: dask-cudf library
